"""De-identification of DICOM datasets.

Implements a practical subset of the DICOM PS3.15 Basic Application Level
Confidentiality Profile: remove direct identifiers, replace a small set
of tags with placeholder values, and optionally regenerate UIDs so
de-identified studies cannot be re-linked to the originals via UID.

This is a general-purpose default, not a certified compliance
implementation — institutions with specific regulatory requirements
(HIPAA Safe Harbor, GDPR, local IRB policy) should review
:data:`DEFAULT_TAGS_TO_REMOVE` and extend it for their own PHI
inventory before relying on it for real patient data.
"""

from __future__ import annotations

import copy
from collections.abc import Iterable, Mapping

import pydicom
from pydicom.uid import generate_uid

#: Tags removed entirely by default. Based on the DICOM PS3.15 Basic
#: Application Level Confidentiality Profile's most common direct
#: identifiers.
DEFAULT_TAGS_TO_REMOVE: tuple[str, ...] = (
    "PatientName",
    "PatientBirthDate",
    "PatientBirthTime",
    "PatientAddress",
    "PatientTelephoneNumbers",
    "OtherPatientIDs",
    "OtherPatientNames",
    "PatientMotherBirthName",
    "ReferringPhysicianName",
    "PerformingPhysicianName",
    "OperatorsName",
    "InstitutionName",
    "InstitutionAddress",
    "InstitutionalDepartmentName",
    "RequestingPhysician",
    "PhysiciansOfRecord",
    "NameOfPhysiciansReadingStudy",
)

#: Tags replaced with a fixed placeholder value rather than removed,
#: because downstream code commonly depends on their presence.
DEFAULT_TAGS_TO_REPLACE: dict[str, str] = {
    "PatientID": "ANONYMIZED",
}

#: UID tags regenerated by default when ``regenerate_uids=True``.
DEFAULT_UID_TAGS: tuple[str, ...] = (
    "StudyInstanceUID",
    "SeriesInstanceUID",
    "SOPInstanceUID",
)


def anonymize(
    dataset: pydicom.Dataset,
    *,
    tags_to_remove: Iterable[str] | None = None,
    tags_to_replace: Mapping[str, str] | None = None,
    regenerate_uids: bool = True,
    in_place: bool = False,
) -> pydicom.Dataset:
    """Return a de-identified copy of a DICOM dataset.

    Args:
        dataset: The dataset to de-identify.
        tags_to_remove: DICOM keywords to delete entirely. Defaults to
            :data:`DEFAULT_TAGS_TO_REMOVE`.
        tags_to_replace: DICOM keywords mapped to a placeholder value to
            set instead of removing. Defaults to
            :data:`DEFAULT_TAGS_TO_REPLACE`.
        regenerate_uids: If ``True`` (default), replace
            ``StudyInstanceUID``, ``SeriesInstanceUID``, and
            ``SOPInstanceUID`` with newly generated UIDs, so
            de-identified data cannot be linked back to the source study
            through its UIDs.
        in_place: If ``True``, mutate and return ``dataset`` directly
            instead of a deep copy.

    Returns:
        The de-identified dataset (a new object unless ``in_place`` is
        ``True``). Also sets ``PatientIdentityRemoved`` to ``"YES"`` and
        ``DeidentificationMethod`` to describe what was done, per the
        DICOM standard's convention for flagging de-identified data.
    """
    result = dataset if in_place else copy.deepcopy(dataset)

    remove = tuple(tags_to_remove) if tags_to_remove is not None else DEFAULT_TAGS_TO_REMOVE
    replace = dict(tags_to_replace) if tags_to_replace is not None else DEFAULT_TAGS_TO_REPLACE

    for tag in remove:
        if tag in result:
            delattr(result, tag)

    for tag, value in replace.items():
        setattr(result, tag, value)

    if regenerate_uids:
        for uid_tag in DEFAULT_UID_TAGS:
            if uid_tag in result:
                setattr(result, uid_tag, generate_uid())

    result.PatientIdentityRemoved = "YES"
    result.DeidentificationMethod = "MIAI basic de-identification (PS3.15 subset)"

    return result
